apiVersion: v2
name: nginx-wrapper
description: A wrapper chart for the NGINX Ingress Controller.
type: application
version: 0.1.0
appVersion: "4.10.1"

dependencies:
  - name: ingress-nginx
    alias: nginx
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"