version: "3"

tasks:
  argo-install:
    desck: Install ArgoCD applications and namespace
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - helm dependency build ./charts/argocd
      - helm install argocd ./charts/argocd --namespace argocd
    silent: true
  argo-clean:
    desc: Delete ArgoCD applications and namespace
    cmds:
      - for app in $(kubectl get applications.argoproj.io -n argocd -o name); do
          echo "Patching $app to remove finalizers";
          kubectl patch $app -n argocd --type=json -p='[{"op":"remove","path":"/metadata/finalizers"}]'
        done
      - kubectl delete applications.argoproj.io --all -n argocd
      - kubectl delete namespace argocd
    silent: true
