{{- include "common.deployment" . | nindent 0 }}
---
{{- include "common.service" . | nindent 0 }}
---
{{- include "common.ingress-route" . | nindent 0 }}
---
{{- include "common.middleware" . | nindent 0 }}
---
{{- include "api-prometheus-proxy.configmap" . | nindent 0 }}
