apiVersion: v2
name: traefik-wrapper
description: A wrapper chart for deploying Traefik with custom configuration for this project.
type: application
version: 0.1.0
appVersion: 3.0.0
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "Traefik"

dependencies:
  - name: traefik
    version: "37.0.0"
    repository: "https://helm.traefik.io/traefik"
