# This ConfigMap is created by a Helm hook before the main deployment is applied.
# This resolves a race condition where the pod fails to start because it's trying
# to mount a ConfigMap that is supposed to be created by its own init container.
# By creating it empty first, the pod can mount it, and the vault-agent-init
# container can then update it with the secrets from Vault.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vault.configMapName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "common.labels" . | nindent 4 }}
data: {}
