apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-secrets
data:
  config.hcl: |
    auto_auth {

      method {
        type = "token_file"

        config {
          token_file_path = "/Users/ethantlee/.vault-token"
        }
      }
    }

    template_config {
      static_secret_render_interval = "5m"
      exit_on_retry_failure         = true
      max_connections_per_host      = 10
    }

    vault {
      address = "https://vault.spitikos.dev"
    }

    env_template "API_GITHUB_TOKEN" {
      contents             = "{{- with secret \"secret/data/spitikos/api\" }}{{ .Data.data.GITHUB_TOKEN }}{{ end }}"
      error_on_missing_key = true
    }

    exec {
      command                   = ["env"]
      restart_on_secret_changes = "always"
      restart_stop_signal       = "SIGTERM"
    }
