keda:
  resources:
    operator:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    metricsServer:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  prometheus:
    metricServer:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: prometheus
