apiVersion: v2
name: redis-wrapper
description: A wrapper Helm chart for the Bitnami Redis chart.
type: application
version: 22.0.5
appVersion: 8.2.1
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "Redis"

dependencies:
  - name: redis
    version: 22.0.5
    repository: "https://charts.bitnami.com/bitnami"
