{{- if .Values.configJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vault.fullname" . }}-config-hook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "vault.fullname" . }}-config-hook
      labels:
        {{- include "vault.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vault.fullname" . }}-config-hook
      restartPolicy: OnFailure
      containers:
        - name: config
          image: "hashicorp/vault:1.20.1"
          command: ["/bin/sh", "/config/configure.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "vault.fullname" . }}-config-hook
            defaultMode: 0777
{{- end }}
